import { useContext, useEffect, useState } from "react";
import Head from "next/head";
import { faX } from '@fortawesome/free-solid-svg-icons';
import { ShoppingCartContext } from "@/contexts/ShoppingCartContext";
import { IProduct } from "@/types";
import Image from "next/image";
import { Button, ButtonContainer, DeleteIcon, InputGroup, LoginTitle, Main, PaymentShipping, PaymentTitle, PaymentTotal, PaymentValue, Product, ProductName, ProductPrice, Separator, ShoppingCartContainer, ShoppingCartPayment, SubTitle, Title } from "./styles";


export default function ShoppingCart() {
    const { getProducts } = useContext(ShoppingCartContext);
    const [products, setProduts] = useState<IProduct[]>([]);

    useEffect(() => {
        const values = getProducts();
        setProduts(values)
    }, [getProducts])

    return (
        <>
            <Head>
                <title>ImagineShop - Cart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.ico" />
            </Head>
            <Main>
                <Title>Meu carrinho</Title>
                <SubTitle>Produtos</SubTitle>
                <ShoppingCartContainer>
                    <section>
                        {
                            products && products.map(product => (
                                <div key={product._id}>
                                    <Separator />
                                    <ButtonContainer>
                                        <button>

                                            <DeleteIcon icon={faX}></DeleteIcon>
                                        </button>
                                    </ButtonContainer>
                                    <Product>
                                        <div>
                                            <Image src={product.image} width={180} height={180} alt={product.name} />
                                        </div>
                                        <ProductName>{product.name}</ProductName>
                                        <ProductPrice>{product.formattedPrice}</ProductPrice>
                                    </Product>

                                </div>
                            ))
                        }
                    </section>
                    <section>
                        <ShoppingCartPayment>
                            <PaymentTitle>Resumo do pedido</PaymentTitle>
                            <PaymentValue><span>{products.length} Produtos</span> <span>R$00,00</span></PaymentValue>
                            <PaymentShipping><span>Frete</span> <span>R$00,00</span></PaymentShipping>

                            <PaymentTotal><span>Total</span> <span>R$00,00</span></PaymentTotal>
                            <Separator />
                            <LoginTitle>Login</LoginTitle>
                            <InputGroup>
                                <span>E-mail:</span>
                                <input type="text" />
                            </InputGroup>
                            <InputGroup>
                                <span>Senha:</span>
                                <input type="password" />
                            </InputGroup>
                            <Button>
                                Continuar
                            </Button>
                        </ShoppingCartPayment>
                    </section>
                </ShoppingCartContainer>
            </Main>
        </>

    )
}