
import Head from 'next/head';


export default function About() {
    return (
        <>
            <Head>
                <title>Imagine Shop - About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.ico" />
            </Head>
            <>
                <h1>ABOUT PAGE</h1>
            </>

        </>
    )
}