
import Banner from '@/components/Banner';
import BannerImage from '@/assets/banner1.png';

import Head from 'next/head';
import styled from 'styled-components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Imagine Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <Main>
        <Banner image={BannerImage} width={1140} heigth={325} />
      </Main>

    </>
  )
}
const Main = styled.main`
    min-height: 62vh;
 `;