import Head from 'next/head'

import { Main } from './styles'

export default function Success() {
    return (
        <>
            <Head>
                <title>ImagineShop - Success</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.ico" />
            </Head>
            <Main>
                <span>Compra realizada com sucesso!</span>
            </Main>
        </>
    )
}